# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MANIFOLD
email: ben@manifold-design.co.uk
description: Web design + development done right.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://manifold-design.co.uk" # the base hostname & protocol for your site
twitter_username: _muzzlehatch
github_username:  muzzlehatch

# Build settings
markdown: kramdown
sass:
    # style: compressed
    sass_dir: _sass
